module VerifyExamples.Cldr.Format.Date.Format0 exposing (spec0)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Cldr.Format.Date exposing (..)
import Cldr.Format.Length exposing (Length(..))
import Cldr.Locale exposing (en)
import Date
import Expect
import Test
import Time exposing (Month(..))


spec0 : Test.Test
spec0 =
    Test.test "#format: \n\n    let\n        date = Date.fromCalendarDate 2000 Jan 1\n    in\n    format (WithLength Short) en date\n    --> \"1/1/00\"" <|
        \() ->
            Expect.equal
                (let
                    date =
                        Date.fromCalendarDate 2000 Jan 1
                 in
                 format (WithLength Short) en date
                )
                "1/1/00"
