module VerifyExamples.Cldr.Format.Date.Format0 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Test
import Expect

import Cldr.Format.Date exposing (..)
import Time exposing (Month(..))
import Date
import Cldr.Locale.En exposing (en)
import Cldr.Format.Length exposing (Length(..))







spec0 : Test.Test
spec0 =
    Test.test "#format: \n\n    format Short en (Date.fromCalendarDate 2000 Jan 1)\n    --> \"1/1/00\"" <|
        \() ->
            Expect.equal
                (
                format Short en (Date.fromCalendarDate 2000 Jan 1)
                )
                (
                "1/1/00"
                )