module VerifyExamples.Cldr.Locale.FromString1 exposing (..)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Cldr.Locale exposing (..)
import Expect
import Test


spec1 : Test.Test
spec1 =
    Test.test "#fromString: \n\n    fromString basicLocales \"en\"\n    --> Just en" <|
        \() ->
            Expect.equal
                (fromString basicLocales "en")
                (Just en)
