module VerifyExamples.Cldr.Locale.ToUnicode0 exposing (spec0)

-- This file got generated by [elm-verify-examples](https://github.com/stoeffel/elm-verify-examples).
-- Please don't modify this file by hand!

import Cldr.Locale exposing (..)
import Cldr.Locale.En exposing (en_GB)
import Expect
import Test


spec0 : Test.Test
spec0 =
    Test.test "#toUnicode: \n\n    toUnicode en_GB\n    --> \"en-GB\"" <|
        \() ->
            Expect.equal
                (toUnicode en_GB)
                "en-GB"
